name: rmbg2_desktop_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - customtkinter
      - onnxruntime>=1.19
      - numpy
      - Pillow
      - pyinstaller
